DROP TABLE links;
DROP TABLE subjects;

CREATE TABLE subjects (
    id SERIAL PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    short_name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    link VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    subject_id INTEGER REFERENCES subjects(id) NOT NULL
);
