GRANT ALL ON DATABASE cdi13 TO cdi13;

GRANT ALL PRIVILEGES ON TABLE subject TO cdi13;
GRANT ALL PRIVILEGES ON TABLE link TO cdi13;
GRANT ALL PRIVILEGES ON TABLE markdown TO cdi13;
GRANT ALL PRIVILEGES ON TABLE full_link_view TO cdi13;

GRANT ALL PRIVILEGES ON SEQUENCE link_id_seq TO cdi13;
GRANT ALL PRIVILEGES ON SEQUENCE subject_id_seq TO cdi13;
GRANT ALL PRIVILEGES ON SEQUENCE markdown_id_seq TO cdi13;
